{
 "title": "Litter Robot",
 "time": { "from": "2024-06-23T22:06:31.066Z", "to": "2024-06-23T23:04:57.781Z" },
 "panels": [
  {
   "title": "Robot Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "robot_litter_level", "legendFormat": "{{robot_name}}" }
   ]
  },
  {
   "title": "Robot Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "robot_litter_level", "legendFormat": "{{robot_model}}" }
   ]
  },
  {
   "title": "Full Indicator",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(robot_is_waste_drawer_full)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scoops Saved (Cycle Count)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(robot_cycle_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Online Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(robot_is_online)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "robot_waste_drawer_level", "legendFormat": "{{robot_status}}" }
   ]
  },
  {
   "title": "Status Over TIme",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 3 },
   "targets": [
    { "expr": "robot_litter_level", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Waste Level",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(robot_waste_drawer_level)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Waste Level Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(max_over_time(robot_waste_drawer_level[5m]))",
     "legendFormat": "Waste Level"
    }
   ]
  },
  {
   "title": "Clean Litter Level",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(robot_litter_level[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clean Litter Level Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(max_over_time(robot_litter_level[5m]))",
     "legendFormat": "Clean Litter Level"
    }
   ]
  }
 ]
}